# Numpy and Pandas exercise

1) Import pandas and numpy

In [1]:
import numpy as np
import pandas as pd

2) Set Numpy's random number generator seed to 101

and 

3) Create a NumPy Matrix of 100 rows by 5 columns consisting of random integers from 1-100. (Keep in mind that the upper limit may be exclusive.)

In [8]:
np.random.seed(101)
mat = np.random.randint(1, 101, (100, 5))
print(mat[0:10, :])

[[ 96  12  82  71  64]
 [ 88  76  10  78  41]
 [  5  64  41  61  93]
 [ 65   6  13  94  41]
 [ 50  84   9  30  60]
 [ 35  45  73  20  11]
 [ 77  96  88   1  74]
 [  9  63  37  84 100]
 [ 29  64   8  11  53]
 [ 57  39  74  53  19]]


4) Now use `pd.DataFrame()` to read-in this numpy array as a dataframe. Simply pass in the numpy array into that function to get back a dataframe. Pandas will auto label the columns to 0-4.

In [9]:
df = pd.DataFrame(mat)
print(df.head(n = 10))

    0   1   2   3    4
0  96  12  82  71   64
1  88  76  10  78   41
2   5  64  41  61   93
3  65   6  13  94   41
4  50  84   9  30   60
5  35  45  73  20   11
6  77  96  88   1   74
7   9  63  37  84  100
8  29  64   8  11   53
9  57  39  74  53   19


5) Using your previously created DataFrame, use `df.columns = [...]` to rename the pandas columns to be `['f1','f2','f3','f4','label']`. You can read about it in [this SO question](https://stackoverflow.com/questions/11346283/renaming-columns-in-pandas).

In [12]:
df.columns = ["f1", "f2", "f3", "f4", "label"]
print(df.head(n = 10))

   f1  f2  f3  f4  label
0  96  12  82  71     64
1  88  76  10  78     41
2   5  64  41  61     93
3  65   6  13  94     41
4  50  84   9  30     60
5  35  45  73  20     11
6  77  96  88   1     74
7   9  63  37  84    100
8  29  64   8  11     53
9  57  39  74  53     19


6) Alright, all the other tasks were hopefully straightforward. This final task will allow you to quickly check to see if you are at the right level with pandas! Do the following:

Create a dataframe with the columns `['A','B','C','D']` with each column having 50 rows of random numbers for data. The random numbers should be between 0 and 100. (Hint: Use numpy to create the numbers, then pass it in to `pd.DataFrame()`, check out the `data` and `columns` parameters for that call.)

In [13]:
df = pd.DataFrame(
    data = np.random.randint(1, 101, (50, 4)),
    columns = ["A", "B", "C", "D"]
)
print(df.head(n = 10))

     A   B   C   D
0   16  96  92  20
1   70   2  78  64
2   88  29  71   6
3    4  13  63  27
4   97  62  88  75
5  100  98  65  96
6    4  89  60  39
7   30  32  89  58
8   10  63  32  14
9   36  48   3  18
